# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Roy Wijaya
tagline:          'Software Engineer'
description:      'A simple software engineer'
url:              https://lymsia.github.io
baseurl:          '/'

paginate:         5

