# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Roy Wijaya
tagline:          'A Jekyll theme'
description:      'A simple software engineer whos trying to understand on this never ending journey'
url:              https://lymsia.github.io
baseurl:          /

paginate:         5

