# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Roy Wijaya
tagline:          'System Engineer'
description:      'A simple software engineer'
url:              https://lymsia.github.io
baseurl:          /

paginate:         5

